#TODO LOAD SETTINGS FROM CONFIG FILE
#TODO MAKE SURE BOTH KEYBOARD AND CONTROLLER INPUT GET TREATED EQUALLY

#TODO MAKE SURE SETTINGS WORK WITH SOMETHING THAT INTERPRETS KEYS

import ConfigParser

config = ConfigParser.ConfigParser()
config.read('config.ini')
print(config.sections())

'''
#[DEVICE SETTINGS]
MAC_ADDRESS = config['DEVICE SETTINGS']['MAC_ADDRESS']
BLUETOOTH_CHANNEL = config['DEVICE SETTINGS']['BLUETOOTH_CHANNEL']
'''

print (config['DEVICE_SETTINGS']['MAC_ADDRESS'])
print (config['DRIVE_SETTINGS']['BLUETOOTH_CHANNEL'])