#TODO MAKE METHODS TO UPDATE BINDINGS.INI FILE AS WELL AS ON THE FLY UPDATE PROGRAM SETTSING FROM THAT FILE.
#TODO MAKE METHODS TO CHECK IF KEYS ARE USED FOR SOMETHING ELSE AND UNBIND THEM.
#TODO SETTINGS LIKE VERBOSE

